# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.

   # - name: WhitespaceTokenizer
   # - name: RegexFeaturizer
   # - name: "SpacyNLP"
   # - name: "SpacyTokenizer"

   # - name: sentiment.SentimentAnalyzer
   # - name: LexicalSyntacticFeaturizer
   # - name: CountVectorsFeaturizer
   # - name: CountVectorsFeaturizer
   #   analyzer: char_wb
   #   min_ngram: 1
   #   max_ngram: 4
   # - name: DIETClassifier
   #   epochs: 100
   # - name: EntitySynonymMapper
   # - name: ResponseSelector
   #   epochs: 100
   # - name: FallbackClassifier
   #   threshold: 0.3
   #   ambiguity_threshold: 0.1
   - name: "SpacyNLP"
   - name: "SpacyTokenizer"
   - name: "SpacyFeaturizer"
   - name: "sentiment.SentimentAnalyzer"    
   - name: "RegexFeaturizer"
   - name: "CRFEntityExtractor"
   - name: "EntitySynonymMapper"
   # - name: "SklearnIntentClassifier" 

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     transformer_size:
       text: 128
       action_text: 128
       label_action_text: 128
       dialogue: 128
       number_of_transformer_layers:
         text: 1
         action_text: 1
         label_action_text: 1
         dialogue: 1
       dense_dimension:
         text: 128
         action_text: 128
         label_action_text: 128
         intent: 20
         action_name: 20
         label_action_name: 20
         entities: 20
         slots: 20
         active_loop: 20
   - name: RulePolicy

